### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [chrissimpkins/codeface#117]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by chrissimpkins** [comment]
Thanks for raising awareness about this Alison.  This is a very important issue.  We have not defined a formal code of conduct for the project but I fully endorse and enforce the ideas in COC's like the [Contributor Covenant](http://contributor-covenant.org/version/1/3/0/) across all projects that I maintain.  We've discussed making this explicit in the Hack project and are likely headed in this direction.  I am open to doing the same here.

Since you raised the issue, would you like to discuss this further and consider the contribution of a document by pull request?

**Comment by chrissimpkins** [comment]
@alison985 checking in with you again on this issue.  Thoughts?
