### ISSUE TITLE
Add Ricty font

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#128]
Developer states that the license does not permit redistribution.

**Comment by chrissimpkins** [comment]
https://github.com/yascentur/Ricty

**Comment by chrissimpkins** [comment]
@mkasu Seeing this in the Ricty font generator script: 

> it is PROHIBITED to distribute the generated font.

```
Copyright (c) 2011-2015, Yasunori Yusa <yascentur at gmail.com>
All rights reserved.

This script is to generate \`\`Ricty'' font from Inconsolata and Migu 1M.
It requires 2-5 minutes to generate Ricty. Owing to SIL Open Font License
Version 1.1 section 5, it is PROHIBITED to distribute the generated font.
```
@yascentur can you confirm whether it is appropriate or not to redistribute Ricty in the Codeface repositories?  @mkasu requested the inclusion of Ricty in our new CJK typeface gallery that is in development [here](https://github.com/chrissimpkins/codeface/blob/cjk/CJK.md).

**Comment by yascentur** [comment]
I guess it is not appropriate to redistribute Ricty.
Ricty is a combined font of Inconsolata ([SIL Open Font License](http://scripts.sil.org/ofl)) and Migu 1M ([IPA Font License](http://ipafont.ipa.go.jp/ipa_font_license_v1-html)).
Each license requires that a modified font must inherit the license.
However, due to OFL section 5, "the Font Software ... must be distributed entirely under this license, and must not to be distributed under any other license."
By the way, [Ricty Diminished](https://github.com/yascentur/RictyDiminished), which does not include IPA font glyphs, is distributed entirely under OFL.
It can be redistibuted under OFL.

**Comment by chrissimpkins** [comment]
@yascentur thank you very much for the clarification.

**Comment by chrissimpkins** [comment]
@mkasu Will not be able to add Ricty to the repository.  Please see message by @yascentur [here](https://github.com/chrissimpkins/codeface/issues/128#issuecomment-170302383)

**Comment by mkasu** [comment]
@chrissimpkins Sorry for confusion with licenses. My request actually included/meant Ricty Diminished, which is the one I currently use. Thanks for your efforts.

**Comment by chrissimpkins** [comment]
@mkasu Japanese font as well and appropriate for the CJK gallery?

**Comment by mkasu** [comment]
@chrissimpkins Yes. It's very similar and uses the same compilation script, but with another set of Japanese glyphes (quite similar), which results in different licensing agreements.

**Comment by chrissimpkins** [comment]
Thanks @mkasu
