### ISSUE TITLE
Add Mensch font

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/codeface#19]
http://robey.lag.net/2010/06/21/mensch-font.html 

Unclear licensing.  Contacted @robey ~~through Twitter to request clarification about redistribution through this repository.  Await response.~~

**Update**: response re: licensing below

**Comment by robey** [comment]
Mensch is just a set of tweaks to Menlo, which is a set of tweaks to Bitstream Vera Sans Mono. Because of that, I think they all share the BVSM license: http://dejavu-fonts.org/wiki/index.php?title=License

If not, I explicitly disclaim any rights to that font, and you may do with it as you want.

Btw, cool project. Feel free to add Metrickal if it looks interesting to you -- I built that one from scratch and posted it to github: https://github.com/robey/metrickal-typeface

**Comment by chrissimpkins** [comment]
Excellent! Thanks much.  I will apply the license to Mensch.

And will definitely add Metrickal.  Great font! #43
